project:
  type: website
  output-dir: _site

website:
  title: "R!sk 2026"
  favicon: images/favicon.ico
  site-url: "https://rconsortium.github.io/risk_website/"
  google-analytics: "G-VJ9272JT9S"
  navbar:
    left:
      - text: Call for Proposals
        href: cfp.qmd
      - text: Code of Conduct
        href: attend.qmd

format:
  html:
    theme: cosmo
    toc: true
